title: RyanJTurner.com
author: Ryan J. Turner, Ph.D.
email: RyanJTurnerPhD at gmail.com
description: >
  A personal and business blog about leadership and consulting, dedicated to my children.

twitter_username: DrRyanTurner
github_username:  rjturner

theme: minima
